// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AutoRestApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PagedCollectionResponseProductsDTO
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PagedCollectionResponseProductsDTO class.
        /// </summary>
        public PagedCollectionResponseProductsDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PagedCollectionResponseProductsDTO class.
        /// </summary>
        public PagedCollectionResponseProductsDTO(IList<ProductsDTO> items = default(IList<ProductsDTO>), string nextPage = default(string), string previousPage = default(string))
        {
            Items = items;
            NextPage = nextPage;
            PreviousPage = previousPage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<ProductsDTO> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nextPage")]
        public string NextPage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previousPage")]
        public string PreviousPage { get; set; }

    }
}
