// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AutoRestApiClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductsDTO
    {
        /// <summary>
        /// Initializes a new instance of the ProductsDTO class.
        /// </summary>
        public ProductsDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductsDTO class.
        /// </summary>
        public ProductsDTO(string productName, int? productId = default(int?), string quantityPerUnit = default(string), double? unitPrice = default(double?), int? supplierId = default(int?), int? categoryId = default(int?), string categoryName = default(string), string supplierCompanyName = default(string))
        {
            ProductId = productId;
            ProductName = productName;
            QuantityPerUnit = quantityPerUnit;
            UnitPrice = unitPrice;
            SupplierId = supplierId;
            CategoryId = categoryId;
            CategoryName = categoryName;
            SupplierCompanyName = supplierCompanyName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantityPerUnit")]
        public string QuantityPerUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitPrice")]
        public double? UnitPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierId")]
        public int? SupplierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryName")]
        public string CategoryName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierCompanyName")]
        public string SupplierCompanyName { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ProductName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProductName");
            }
            if (ProductName != null)
            {
                if (ProductName.Length > 40)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ProductName", 40);
                }
                if (ProductName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ProductName", 0);
                }
            }
            if (UnitPrice > 999.99)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "UnitPrice", 999.99);
            }
            if (UnitPrice < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "UnitPrice", 0);
            }
        }
    }
}
