/* 
 * My NProducts API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PagedCollectionResponseProductsDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PagedCollectionResponseProductsDTOTests
    {
        // TODO uncomment below to declare an instance variable for PagedCollectionResponseProductsDTO
        //private PagedCollectionResponseProductsDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PagedCollectionResponseProductsDTO
            //instance = new PagedCollectionResponseProductsDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PagedCollectionResponseProductsDTO
        /// </summary>
        [Test]
        public void PagedCollectionResponseProductsDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PagedCollectionResponseProductsDTO
            //Assert.IsInstanceOfType<PagedCollectionResponseProductsDTO> (instance, "variable 'instance' is a PagedCollectionResponseProductsDTO");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'PreviousPage'
        /// </summary>
        [Test]
        public void PreviousPageTest()
        {
            // TODO unit test for the property 'PreviousPage'
        }

    }

}
